"use client";
import { Inter } from "next/font/google";
import { AnimatePresence } from "framer-motion";
const inter = Inter({ subsets: ["latin"] });
import { ReactLenis, useLenis } from "@studio-freight/react-lenis";
// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({ children, params }) {
  const lenis = useLenis(({ scroll }) => {
    // called every scroll
  })
  
  return (
    <ReactLenis root options={{ lerp: 0.08, wheelMultiplier: 0.5 }}>


    <html lang="en">
      <AnimatePresence
        initial={true}
        onExitComplete={() => console.log("jj")}
      >
          <body className={inter.className}>{children}</body>
      </AnimatePresence>
    </html>
    </ReactLenis>

  );
}
