"use client";
import { useEffect } from "react";
import { Inter } from "next/font/google";
import { AnimatePresence } from "framer-motion";
const inter = Inter({ subsets: ["latin"] });
import { ReactLenis, useLenis } from "@studio-freight/react-lenis";
// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({ children, params }) {
  const lenis = useLenis(({ scroll }) => {
    // called every scroll
  })
  useEffect(() => {
    if (lenis && lenis.scrollTo) {
      lenis.scrollTo({ top: 0, behavior: 'smooth' }); 
      // assuming lenis.scrollTo accepts an object with a similar structure to window.scrollTo
    }
  }, [params.slug, lenis]); // This effect will run every time params.slug changes, or lenis is defined

  return (
    <ReactLenis root options={{ lerp: 0.08, wheelMultiplier: 0.5 }}>


    <html lang="en">
      
      <AnimatePresence
        initial={true}
  
      >
       
          <body key={params.slug} className={inter.className}>{children}</body>
      </AnimatePresence>
    </html>
    </ReactLenis>

  );
}
