"use client";
import { Inter } from "next/font/google";
import { AnimatePresence } from "framer-motion";
import { usePathname, useSearchParams } from "next/navigation";
const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({ children, params }) {
  const pathname = usePathname();
console.log(pathname)
  return (
    <html lang="en">
      <AnimatePresence initial={false} mode="popLayout">
        <body className={inter.className}>
          {children}
        </body>
      </AnimatePresence>
    </html>
  );
}
